# Generated by Django 4.1.3 on 2022-12-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Ismi')),
                ('content', models.TextField(verbose_name='Malumot')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('img', models.CharField(max_length=255, verbose_name='Rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('content', models.TextField(verbose_name='malumot')),
                ('tanlov', models.CharField(max_length=255, verbose_name='tanlov')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='vaqti')),
                ('rasm', models.CharField(max_length=255, verbose_name='rasm')),
            ],
        ),
        migrations.CreateModel(
            name='TopPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('tanlov', models.CharField(max_length=255, verbose_name='Tanlov')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('rasm', models.CharField(max_length=255, verbose_name='Rasm')),
            ],
        ),
    ]
